# Generated by Django 6.0.1 on 2026-01-24 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL friendly version of the title', unique=True)),
                ('summary', models.TextField()),
                ('cover_image', models.URLField(blank=True, help_text='URL to a cover image (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField(help_text='Chapter number (1, 2, 3...)')),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When should this be visible?')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='stories.story')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('story', 'number')},
            },
        ),
    ]
